COMMON:
  SECRETS_PATH: "../secrets.json"
  LOG_DIR: "../logs"
  USE_PROXY_ALPHA: 1.0

ALL:
  NUM_ITEMS: 100000
  RUN_EVERY: 50
  IS_WOMEN_ALPHA: 0.7
  SORT_BY_DATE_ALPHA: 0.2

FROM_INTERACTIONS:
  NUM_ITEMS: 1000
  NUM_NEIGHBORS: 50

SAVED:
  NUM_ITEMS: 1000
  JOB_ID: "saved"
  ASCENDING_ALPHA: 0.5 