COMMON:
  SECRETS_PATH: "../secrets.json"
  LOG_DIR: "../logs"
  USE_PROXY_ALPHA: 1.0
  PROXY_PASSWORD_POSITION: 3

ALL:
  NUM_ITEMS: 50000
  RUN_EVERY: 50
  IS_WOMEN_ALPHA: .7
  SORT_BY_DATE_ALPHA: .4
  CATALOG_SCORE_WEIGHTS: [.9, .1, 0.]

FROM_INTERACTIONS:
  NUM_ITEMS: 1000
  NUM_NEIGHBORS: 50
  SORT_BY_DATE_ALPHA: 0.
  DAYS_LOOKBACK: 14

SAVED:
  NUM_ITEMS: 1000
  JOB_ID: "saved"
  ASCENDING_ALPHA: 0.5 