COMMON:
  SECRETS_PATH: "../secrets.json"
  LOG_DIR: "../logs"
  USE_PROXY_ALPHA: 1.0
  PROXY_PASSWORD_POSITION: 1

ALL:
  NUM_ITEMS: 200000
  RUN_EVERY: 50
  IS_WOMEN_ALPHA: .7
  SORT_BY_DATE_ALPHA: .5
  CATALOG_SCORE_WEIGHTS: [1., 0., 0.]

FROM_INTERACTIONS:
  NUM_ITEMS: 2000
  NUM_NEIGHBORS: 50
  SORT_BY_DATE_ALPHA: .5
  DAYS_LOOKBACK: 14

SAVED:
  NUM_ITEMS: 1000
  JOB_ID: "saved"
  ASCENDING_ALPHA: 0.5 