name: Availability - User Interactions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  availability-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t availability .

      - name: Run Docker Container
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
          FROM_INTERACTIONS: true
        run: docker run -e SECRETS_JSON -e FROM_INTERACTIONS availability 